name: cpv-filereader-py8hi-raw-file-reader
defaults:
  log_task_output: none
  _module_cmdline: >-
    source /etc/profile.d/modules.sh && MODULEPATH={{ modulepath }} module load O2 QualityControl Control-OCCPlugin &&
    {{ dpl_command }} | o2-raw-file-reader-workflow
  _plain_cmdline: "source /etc/profile.d/o2.sh && {{ dpl_command }} | o2-raw-file-reader-workflow"
control:
  mode: "fairmq"
wants:
  cpu: 0.01
  memory: 1
bind:
  - name: from_raw-file-reader_to_CPVRawToDigitConverterSpec
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "{{ fmq_rate_logging }}"
command:
  shell: true
  log: "{{ log_task_output }}"
  env: ["O2_DETECTOR={{ detector }}"]
  user: "{{ user }}"
  value: "{{ len(modulepath)>0 ? _module_cmdline : _plain_cmdline }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "'{{ monitoring_dpl_url }}'"
    - "--session"
    - "'{{ session_id }}'"
    - "--infologger-severity"
    - "'{{ infologger_severity }}'"
    - "--infologger-mode"
    - "'{{ infologger_mode }}'"
    - "--driver-client-backend"
    - "'stdout://'"
    - "--shm-segment-size"
    - "'{{ shm_segment_size }}'"
    - "--shm-throw-bad-alloc"
    - "'{{ shm_throw_bad_alloc }}'"
    - "--resources-monitoring"
    - "'{{ resources_monitoring }}'"
    - "--id"
    - "'raw-file-reader'"
    - "--shm-monitor"
    - "'false'"
    - "--log-color"
    - "'false'"
    - "--aod-memory-rate-limit"
    - "'0'"
    - "--aod-writer-json"
    - "''"
    - "--aod-writer-keep"
    - "''"
    - "--aod-writer-ntfmerge"
    - "-1"
    - "--aod-writer-resfile"
    - "''"
    - "--aod-writer-resmode"
    - "'RECREATE'"
    - "--buffer-size"
    - "'5120'"
    - "--channel-prefix"
    - "''"
    - "--clone"
    - "''"
    - "--configKeyValues"
    - "''"
    - "--delay"
    - "'0'"
    - "--drop-tf"
    - "'none'"
    - "--fairmq-ipc-prefix"
    - "'/tmp'"
    - "--fairmq-rate-logging"
    - "'0'"
    - "--fairmq-recv-buffer-size"
    - "'4'"
    - "--fairmq-send-buffer-size"
    - "'4'"
    - "--forwarding-destination"
    - "'drop'"
    - "--forwarding-policy"
    - "'dangling'"
    - "--input-conf"
    - "'/home/cpv/O2tests/evd/pythia8hi/raw/CPV/CPVraw.cfg'"
    - "--labels"
    - "''"
    - "--loop"
    - "-1"
    - "--max-tf"
    - "'4294967295'"
    - "--min-tf"
    - "'0'"
    - "--nocheck-tf-start-mismatch"
    - "--pipeline"
    - "''"
    - "--raw-channel-config"
    - "''"
    - "--readers"
    - "'1'"
    - "--severity"
    - "'info'"
    - "--shm-mlock-segment"
    - "'false'"
    - "--shm-mlock-segment-on-creation"
    - "'false'"
    - "--shm-segment-id"
    - "'0'"
    - "--shm-zero-segment"
    - "'false'"
    - "--spawners"
    - "'1'"
    - "--stacktrace-on-signal"
    - "'all'"
    - "--super-page-size"
    - "'1048576'"
    - "--workflow-suffix"
    - "''"
